<?PHP
NAMESPACE HARDNESS;
/**
* ESTE CÓDIGO PHP IRÁ SUBSTITUIR O CALLBACK: CAMPOMOSTRADEPARTAMENTO()
*/
FUNCTION _CAMPOMOSTRADEPARTAMENTO ($ARRAY){
	RETURN $ARRAY['TODOSCAMPOS']['C008_TIPO'];
}
